import { CardImage } from "../assets";
 const dbProducts = [
  {
    id: 12,
    name: "Sony PS5 Marvel's Spiderman Miles Morales (PS5)",
    currentPrice: 2579,
    mrp: 3999,
    rating: 4.5,
    discount: "36%",
    outOfStock: true,
    brand: "Sony",
    productImg: CardImage,
    addedToWishList: true,
    isBestSeller: true,
    addedToCart: false,
    categoryName: "PlayStation",
    accessoriesType: "Games",
  },
  {
    id: 13,
    name: "PS5 Sackboy : A Big Adventure",
    currentPrice: 2790,
    mrp: 3999,
    rating: 4,
    discount: "30%",
    outOfStock: false,
    brand: "Sony",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Games",
  },
  {
    id: 13,
    name: "PS5 Demon's Souls",
    currentPrice: 3040,
    mrp: 4999,
    rating: 4,
    discount: "39%",
    outOfStock: false,
    brand: "Sony",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Games",
  },
  {
    id: 13,
    name: "PS5 RATCHET & CLANK: RIFT APART",
    currentPrice: 2699,
    mrp: 4999,
    rating: 3,
    discount: "46%",
    outOfStock: false,
    brand: "Sony",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Games",
  },
  {
    id: 13,
    name: "PS5 RETURNAL",
    currentPrice: 3168,
    mrp: 4999,
    rating: 4.5,
    discount: "37%",
    outOfStock: false,
    brand: "Sony",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Games",
  },
  {
    id: 13,
    name: "Microsoft 1 TB Xbox One S Console - Anthem Bundle",
    currentPrice: 70000,
    mrp: 80000,
    rating: 5,
    discount: "14%",
    outOfStock: false,
    brand: "Microsoft",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Controller",
  },
  {
    id: 12,
    name: "Microsoft Xbox One Wireless Controller with Bluetooth",
    currentPrice: 5900,
    mrp: 6999,
    rating: 4.5,
    discount: "16%",
    outOfStock: true,
    brand: "Microsoft",
    productImg: CardImage,
    addedToWishList: true,
    isBestSeller: true,
    addedToCart: false,
    categoryName: "XBOX",
    accessoriesType: "Controller",
  },
  {
    id: 13,
    name: "Microsoft Xbox Wireless Adapter for Windows - Xbox One",
    currentPrice: 2499,
    mrp: 6999,
    rating: 4.5,
    discount: "64%",
    outOfStock: false,
    brand: "Microsoft",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Controller",
  },
  {
    id: 13,
    name: "Xbox Wireless Controller,White",
    currentPrice: 9999,
    mrp: 15998,
    rating: 5,
    discount: "38%",
    outOfStock: false,
    brand: "Microsoft",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Controller",
  },
  {
    id: 13,
    name: "Logitech G29 Driving Force Racing Wheel ",
    currentPrice: 26995,
    mrp: 36995,
    rating: 4.5,
    discount: "27%",
    outOfStock: false,
    brand: "Logitech",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "Racing Wheel",
  },
  {
    id: 13,
    name: "HORI Officially Licensed Nintendo Switch Mario Kart Racing Wheel ",
    currentPrice: 6399,
    mrp: 7999,
    rating: 4.5,
    discount: "20%",
    outOfStock: false,
    brand: "Hori",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "Nintendo",
    accessoriesType: "Racing Wheel",
  },
  {
    id: 13,
    name: "Thrustmaster T80 |PC Racing Game Wheel | PS3/PS4",
    currentPrice: 11399,
    mrp: 13999,
    rating: 4,
    discount: "19%",
    outOfStock: false,
    brand: "ThrustMaster",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Racing Wheel",
  },
  {
    id: 13,
    name: "Thrustmaster Ferrari 458 Spider | Racing Game Wheel | Xbox One",
    currentPrice: 12499,
    mrp: 14999,
    rating: 4.5,
    discount: "17%",
    outOfStock: false,
    brand: "ThrustMaster",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Racing Wheel",
  },
  {
    id: 13,
    name: "boAt Immortal IM-200 7.1 Wired Over Ear Headphones",
    currentPrice: 1299,
    mrp: 4999,
    rating: 3,
    discount: "74%",
    outOfStock: false,
    brand: "Boat",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "Headset",
  },
  {
    id: 13,
    name: "Hyperx Cloud Core 7.1 Wired On Ear Headphones",
    currentPrice: 6490,
    mrp: 8490,
    rating: 4.5,
    discount: "24%",
    outOfStock: false,
    brand: "HyperX",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "Headset",
  },
  {
    id: 13,
    name: "Xbox Stereo Headset",
    currentPrice: 5098,
    mrp: 5990,
    rating: 4,
    discount: "15%",
    outOfStock: false,
    brand: "Microsoft",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Headset",
  },
  {
    id: 13,
    name: "PULSE 3D™ wireless headset White - (PlayStation®5)",
    currentPrice: 8590,
    mrp: 10000,
    rating: 4.5,
    discount: "17%",
    outOfStock: false,
    brand: "Sony",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Headset",
  },
  {
    id: 13,
    name: "Elgato Game Capture HD60 S - Stream",
    currentPrice: 13499,
    mrp: 21600,
    rating: 4.5,
    discount: "38%",
    outOfStock: false,
    brand: "Elgato",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "Streaming Devices",
  },
  {
    id: 13,
    name: "Elgato Game Capture HD60 Pro 1080p60",
    currentPrice: 16392,
    mrp: 24700,
    rating: 4,
    discount: "34%",
    outOfStock: false,
    brand: "Elgato",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "Streaming Devices",
  },
  {
    id: 13,
    name: "Corsair Elgato Stream Deck Mini - Live Content Creation Controller",
    currentPrice: 10040,
    mrp: 14400,
    rating: 5,
    discount: "30%",
    outOfStock: false,
    brand: "Elgato",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "Streaming Devices",
  },
  {
    id: 13,
    name: "OculusÂ Quest 2 Advanced All-In-One Virtual Reality Headset (128GB)",
    currentPrice: 30999,
    mrp: 69999,
    rating: 4.5,
    discount: "56%",
    outOfStock: false,
    brand: "Oculus",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: true,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "VR",
  },
  {
    id: 13,
    name: "Virtual Reality Headset Glasses",
    currentPrice: 499,
    mrp: 999,
    rating: 2,
    discount: "50%",
    outOfStock: false,
    brand: "Flowres",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "VR",
  },
  {
    id: 13,
    name: "Irusu Play VR Plus Virtual Reality Headset",
    currentPrice: 2699,
    mrp: 3999,
    rating: 3.5,
    discount: "33%",
    outOfStock: false,
    brand: "IRUSU",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "VR",
  },
  {
    id: 13,
    name: "KontrolFreek FPS Freek Galaxy Purple for PlayStation 4",
    currentPrice: 649,
    mrp: 1499,
    rating: 4.5,
    discount: "57%",
    outOfStock: false,
    brand: "KontrolFreek",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Thumb Grips",
  },
  {
    id: 13,
    name: "KontrolFreek Call of Duty: Black Ops 4 Performance Thumbsticks for XBOX Controller",
    currentPrice: 999,
    mrp: 1999,
    rating: 4.5,
    discount: "50%",
    outOfStock: false,
    brand: "KontrolFreek",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Thumb Grips",
  },
  {
    id: 13,
    name: "KontrolFreek FPS Freek Phantom Thumb Grips for PS4",
    currentPrice: 749,
    mrp: 1299,
    rating: 4.5,
    discount: "42%",
    outOfStock: false,
    brand: "KontrolFreek",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Thumb Grips",
  },
  {
    id: 13,
    name: "New World Special Design Army Soft Silicone Case Cover Gel Skin Protective for PS4 Wireless Controller",
    currentPrice: 322,
    mrp: 499,
    rating: 4.5,
    discount: "35%",
    outOfStock: false,
    brand: "New World",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PlayStation",
    accessoriesType: "Cases and Covers",
  },
  {
    id: 13,
    name: "New World Soft Silicone Case cover Protective Skin for XBOX",
    currentPrice: 308,
    mrp: 499,
    rating: 4.5,
    discount: "38%",
    outOfStock: false,
    brand: "New World",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "XBOX",
    accessoriesType: "Cases and Covers",
  },
  {
    id: 13,
    name: "Turtle Beach Recon 50P Black & Blue",
    currentPrice: 999,
    mrp: 2499,
    rating: 4,
    discount: "60%",
    outOfStock: false,
    brand: "Turtle Beach",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "International Brands",
  },
  {
    id: 13,
    name: "PowerA Wired Gaming Controller for Nintendo Switch",
    currentPrice: 2027,
    mrp: 2999,
    rating: 4.5,
    discount: "32%",
    outOfStock: false,
    brand: "PowerA",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "Nintendo",
    accessoriesType: "International Brands",
  },
  {
    id: 13,
    name: "Turtle Beach Recon 70 Green Camo",
    currentPrice: 990,
    mrp: 3499,
    rating: 4.5,
    discount: "72%",
    outOfStock: false,
    brand: "Turtle Beach",
    productImg: CardImage,
    addedToWishList: false,
    isBestSeller: false,
    addedToCart: true,
    categoryName: "PC",
    accessoriesType: "International Brands",
  },
];

export default dbProducts
